# data.py — App definitions registry

ESSENTIAL   = "essential"
RECOMMENDED = "recommended"
OPTIONAL    = "optional"
SKIP        = "skip"

TIER_COLOR  = {ESSENTIAL: "green", RECOMMENDED: "cyan", OPTIONAL: "yellow", SKIP: "red"}
TIER_SYMBOL = {ESSENTIAL: "★", RECOMMENDED: "◆", OPTIONAL: "◇", SKIP: "○"}
TIER_ORDER  = {ESSENTIAL: 0, RECOMMENDED: 1, OPTIONAL: 2, SKIP: 3}

APPS = [
    # ── Editors & IDEs ─────────────────────────────────────
    {"name":"VS Code",                  "category":"Editors & IDEs",        "tier":ESSENTIAL,   "winget_id":"Microsoft.VisualStudioCode",           "check_cmd":["code","--version"],              "version_url":"https://api.github.com/repos/microsoft/vscode/releases/latest",          "web_url":"https://code.visualstudio.com/",                                  "approx_mb":350,  "tags":["machine1","machine2"],       "note":"Core editor — needed everywhere"},
    {"name":"Cursor (AI editor)",       "category":"Editors & IDEs",        "tier":RECOMMENDED, "winget_id":"Anysphere.Cursor",                     "check_cmd":["cursor","--version"],            "version_url":None,                                                                    "web_url":"https://cursor.com/",                                             "approx_mb":400,  "tags":["recommended","ai"],          "note":"VS Code fork with native AI coding"},
    {"name":"Neovim",                   "category":"Editors & IDEs",        "tier":OPTIONAL,    "winget_id":"Neovim.Neovim",                        "check_cmd":["nvim","--version"],              "version_url":"https://api.github.com/repos/neovim/neovim/releases/latest",             "web_url":"https://neovim.io/",                                              "approx_mb":15,   "tags":["recommended"],               "note":"Terminal editor — optional unless you use vim keybindings"},
    {"name":"Visual Studio 2022",       "category":"Editors & IDEs",        "tier":OPTIONAL,    "winget_id":"Microsoft.VisualStudio.2022.Community","check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://visualstudio.microsoft.com/downloads/",                   "approx_mb":5000, "tags":["machine1"],                  "note":"Heavy 5GB+ — only needed for .NET/C++ dev"},
    {"name":"Visual Studio 2026",       "category":"Editors & IDEs",        "tier":OPTIONAL,    "winget_id":"Microsoft.VisualStudio.2026.Community","check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://visualstudio.microsoft.com/downloads/",                   "approx_mb":5000, "tags":["machine2"],                  "note":"Heavy 5GB+ — only needed for .NET/C++ dev"},
    {"name":"JetBrains Toolbox",        "category":"Editors & IDEs",        "tier":SKIP,        "winget_id":"JetBrains.Toolbox",                    "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.jetbrains.com/toolbox-app/",                          "approx_mb":200,  "tags":["recommended"],               "note":"Skip unless you use IntelliJ/PyCharm/Rider"},
    # ── Version Control & API ──────────────────────────────
    {"name":"Git",                      "category":"Version Control & API", "tier":ESSENTIAL,   "winget_id":"Git.Git",                              "check_cmd":["git","--version"],               "version_url":"https://api.github.com/repos/git-for-windows/git/releases/latest",       "web_url":"https://git-scm.com/",                                            "approx_mb":250,  "tags":["machine1","machine2"],       "note":"Version control foundation"},
    {"name":"GitHub CLI",               "category":"Version Control & API", "tier":ESSENTIAL,   "winget_id":"GitHub.cli",                           "check_cmd":["gh","--version"],                "version_url":"https://api.github.com/repos/cli/cli/releases/latest",                  "web_url":"https://cli.github.com/",                                         "approx_mb":50,   "tags":["machine1","machine2"],       "note":"PR/issue/repo management from terminal"},
    {"name":"lazygit",                  "category":"Version Control & API", "tier":RECOMMENDED, "winget_id":"JesseDuffield.lazygit",                "check_cmd":["lazygit","--version"],           "version_url":"https://api.github.com/repos/jesseduffield/lazygit/releases/latest",    "web_url":"https://github.com/jesseduffield/lazygit",                        "approx_mb":15,   "tags":["machine1","cli"],            "note":"Terminal Git UI — very fast workflow"},
    {"name":"Postman",                  "category":"Version Control & API", "tier":RECOMMENDED, "winget_id":"Postman.Postman",                      "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.postman.com/downloads/",                              "approx_mb":500,  "tags":["machine1","machine2"],       "note":"Full-featured API client"},
    {"name":"Bruno (API client)",       "category":"Version Control & API", "tier":RECOMMENDED, "winget_id":"Bruno.Bruno",                          "check_cmd":["bru","--version"],               "version_url":"https://api.github.com/repos/usebruno/bruno/releases/latest",            "web_url":"https://www.usebruno.com/",                                       "approx_mb":150,  "tags":["recommended"],               "note":"Lightweight open-source Postman alt — git-friendly"},
    {"name":"Insomnia",                 "category":"Version Control & API", "tier":OPTIONAL,    "winget_id":"Insomnia.Insomnia",                    "check_cmd":None,                              "version_url":"https://api.github.com/repos/Kong/insomnia/releases/latest",             "web_url":"https://insomnia.rest/download",                                  "approx_mb":300,  "tags":["recommended"],               "note":"Redundant if you have Postman or Bruno"},
    # ── DevOps & Containers ────────────────────────────────
    {"name":"Docker Desktop",           "category":"DevOps & Containers",   "tier":ESSENTIAL,   "winget_id":"Docker.DockerDesktop",                 "check_cmd":["docker","--version"],            "version_url":"https://api.github.com/repos/docker/cli/releases/latest",               "web_url":"https://docs.docker.com/desktop/release-notes/",                  "approx_mb":1500, "tags":["machine2"],                  "note":"Container runtime — essential for modern dev"},
    {"name":"WSL",                      "category":"DevOps & Containers",   "tier":ESSENTIAL,   "winget_id":"Microsoft.WSL",                        "check_cmd":["wsl","--version"],               "version_url":"https://api.github.com/repos/microsoft/WSL/releases/latest",            "web_url":"https://learn.microsoft.com/en-us/windows/wsl/install",           "approx_mb":200,  "tags":["machine1","machine2"],       "note":"Linux on Windows — needed for most dev workflows"},
    {"name":"kubectl",                  "category":"DevOps & Containers",   "tier":RECOMMENDED, "winget_id":"Kubernetes.kubectl",                   "check_cmd":["kubectl","version","--client"],  "version_url":"https://api.github.com/repos/kubernetes/kubernetes/releases/latest",    "web_url":"https://kubernetes.io/releases/",                                 "approx_mb":50,   "tags":["machine2"],                  "note":"K8s CLI — needed if running Kubernetes"},
    {"name":"Terraform",                "category":"DevOps & Containers",   "tier":RECOMMENDED, "winget_id":"Hashicorp.Terraform",                  "check_cmd":["terraform","--version"],         "version_url":"https://api.github.com/repos/hashicorp/terraform/releases/latest",      "web_url":"https://developer.hashicorp.com/terraform/install",               "approx_mb":80,   "tags":["recommended"],               "note":"IaC standard — most teams use Terraform"},
    {"name":"AWS CLI",                  "category":"DevOps & Containers",   "tier":RECOMMENDED, "winget_id":"Amazon.AWSCLI",                        "check_cmd":["aws","--version"],               "version_url":None,                                                                    "web_url":"https://aws.amazon.com/cli/",                                     "approx_mb":100,  "tags":["machine2"],                  "note":"Install only if using AWS"},
    {"name":"Azure CLI",                "category":"DevOps & Containers",   "tier":RECOMMENDED, "winget_id":"Microsoft.AzureCLI",                   "check_cmd":["az","version"],                  "version_url":"https://api.github.com/repos/Azure/azure-cli/releases/latest",          "web_url":"https://learn.microsoft.com/en-us/cli/azure/",                    "approx_mb":200,  "tags":["machine2"],                  "note":"Install only if using Azure"},
    {"name":"Helm",                     "category":"DevOps & Containers",   "tier":OPTIONAL,    "winget_id":"Helm.Helm",                            "check_cmd":["helm","version","--short"],      "version_url":"https://api.github.com/repos/helm/helm/releases/latest",                "web_url":"https://helm.sh/",                                                "approx_mb":40,   "tags":["machine2"],                  "note":"K8s package manager — only if managing Helm charts"},
    {"name":"Minikube",                 "category":"DevOps & Containers",   "tier":OPTIONAL,    "winget_id":"Kubernetes.minikube",                  "check_cmd":["minikube","version"],            "version_url":"https://api.github.com/repos/kubernetes/minikube/releases/latest",      "web_url":"https://minikube.sigs.k8s.io/docs/",                              "approx_mb":200,  "tags":["machine1"],                  "note":"Local K8s cluster — only for K8s dev/testing"},
    {"name":"Google Cloud CLI",         "category":"DevOps & Containers",   "tier":OPTIONAL,    "winget_id":"Google.CloudSDK",                      "check_cmd":["gcloud","--version"],            "version_url":None,                                                                    "web_url":"https://cloud.google.com/sdk/docs/install",                       "approx_mb":300,  "tags":["recommended"],               "note":"Install only if using Google Cloud"},
    {"name":"Pulumi",                   "category":"DevOps & Containers",   "tier":OPTIONAL,    "winget_id":"Pulumi.Pulumi",                        "check_cmd":["pulumi","version"],              "version_url":"https://api.github.com/repos/pulumi/pulumi/releases/latest",            "web_url":"https://www.pulumi.com/docs/install/",                            "approx_mb":100,  "tags":["recommended"],               "note":"Terraform alt using real code — optional"},
    {"name":"Act (GitHub Actions local)","category":"DevOps & Containers",  "tier":SKIP,        "winget_id":"nektos.act",                           "check_cmd":["act","--version"],               "version_url":"https://api.github.com/repos/nektos/act/releases/latest",               "web_url":"https://nektosact.com/",                                          "approx_mb":30,   "tags":["recommended"],               "note":"Skip unless debugging CI pipelines locally"},
    # ── Databases ──────────────────────────────────────────
    {"name":"DBeaver",                  "category":"Databases",             "tier":ESSENTIAL,   "winget_id":"dbeaver.dbeaver",                      "check_cmd":None,                              "version_url":"https://api.github.com/repos/dbeaver/dbeaver/releases/latest",           "web_url":"https://dbeaver.io/download/",                                    "approx_mb":500,  "tags":["machine1","machine2"],       "note":"Connects to all DBs — one tool to rule them all"},
    {"name":"PostgreSQL 17",            "category":"Databases",             "tier":RECOMMENDED, "winget_id":"PostgreSQL.PostgreSQL.17",             "check_cmd":["psql","--version"],              "version_url":None,                                                                    "web_url":"https://www.postgresql.org/download/windows/",                    "approx_mb":600,  "tags":["machine1"],                  "note":"Best relational DB for most projects"},
    {"name":"MongoDB Community",        "category":"Databases",             "tier":RECOMMENDED, "winget_id":"MongoDB.Server",                       "check_cmd":["mongod","--version"],            "version_url":None,                                                                    "web_url":"https://www.mongodb.com/try/download/community",                  "approx_mb":700,  "tags":["machine2"],                  "note":"Document DB — install if your stack uses Mongo"},
    {"name":"MongoDB Compass",          "category":"Databases",             "tier":RECOMMENDED, "winget_id":"MongoDB.Compass.Full",                 "check_cmd":None,                              "version_url":"https://api.github.com/repos/mongodb-js/compass/releases/latest",       "web_url":"https://www.mongodb.com/products/tools/compass",                  "approx_mb":400,  "tags":["machine2"],                  "note":"MongoDB GUI — skip if using DBeaver for Mongo"},
    {"name":"Redis",                    "category":"Databases",             "tier":RECOMMENDED, "winget_id":"Redis.Redis",                          "check_cmd":["redis-cli","--version"],         "version_url":"https://api.github.com/repos/redis/redis/releases/latest",              "web_url":"https://redis.io/download/",                                      "approx_mb":20,   "tags":["recommended"],               "note":"Cache/message broker — needed for most backend stacks"},
    {"name":"Neo4j Desktop",            "category":"Databases",             "tier":OPTIONAL,    "winget_id":"Neo4j.Neo4jDesktop",                   "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://neo4j.com/download/",                                     "approx_mb":1000, "tags":["machine2"],                  "note":"Graph DB — only if your project uses graph data"},
    {"name":"TablePlus",                "category":"Databases",             "tier":OPTIONAL,    "winget_id":"TablePlus.TablePlus",                  "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://tableplus.com/windows",                                   "approx_mb":100,  "tags":["recommended"],               "note":"Polished DB GUI — redundant with DBeaver"},
    {"name":"Qdrant (vector DB)",       "category":"Databases",             "tier":OPTIONAL,    "winget_id":None,                                   "check_cmd":None,                              "version_url":"https://api.github.com/repos/qdrant/qdrant/releases/latest",            "web_url":"https://qdrant.tech/documentation/guides/installation/",          "approx_mb":500,  "tags":["recommended","ai"],          "note":"Fast vector DB for AI/RAG — runs via Docker","install_cmd":["docker","run","-p","6333:6333","-d","qdrant/qdrant"]},
    {"name":"Chroma (vector DB)",       "category":"Databases",             "tier":OPTIONAL,    "winget_id":None,                                   "check_cmd":None,                              "version_url":"https://api.github.com/repos/chroma-core/chroma/releases/latest",       "web_url":"https://docs.trychroma.com/",                                     "approx_mb":200,  "tags":["recommended","ai"],          "note":"Embedded vector DB — great for prototyping RAG","install_cmd":["pip","install","chromadb"]},
    {"name":"Weaviate (vector DB)",     "category":"Databases",             "tier":SKIP,        "winget_id":None,                                   "check_cmd":None,                              "version_url":"https://api.github.com/repos/weaviate/weaviate/releases/latest",        "web_url":"https://weaviate.io/developers/weaviate/installation",            "approx_mb":800,  "tags":["recommended","ai"],          "note":"Skip unless running large-scale production RAG","install_cmd":["docker","pull","semitechnologies/weaviate"]},
    # ── Runtimes & Languages ───────────────────────────────
    {"name":"Node.js LTS",              "category":"Runtimes & Languages",  "tier":ESSENTIAL,   "winget_id":"OpenJS.NodeJS.LTS",                    "check_cmd":["node","--version"],              "version_url":"https://nodejs.org/dist/index.json",                                    "web_url":"https://nodejs.org/en/download/",                                 "approx_mb":80,   "tags":["machine1","machine2"],       "note":"JS runtime — needed for npm, Claude Code, most tooling"},
    {"name":"Python 3.12",              "category":"Runtimes & Languages",  "tier":ESSENTIAL,   "winget_id":"Python.Python.3.12",                   "check_cmd":["python","--version"],            "version_url":"https://api.github.com/repos/python/cpython/releases/latest",           "web_url":"https://www.python.org/downloads/",                               "approx_mb":100,  "tags":["machine1","machine2"],       "note":"Core language for AI/ML and scripting"},
    {"name":"Anaconda3",                "category":"Runtimes & Languages",  "tier":RECOMMENDED, "winget_id":"Anaconda.Anaconda3",                   "check_cmd":["conda","--version"],             "version_url":None,                                                                    "web_url":"https://www.anaconda.com/download",                               "approx_mb":3500, "tags":["machine1","machine2"],       "note":"Data science Python — large 3.5GB but convenient for ML"},
    {"name":"pnpm",                     "category":"Runtimes & Languages",  "tier":RECOMMENDED, "winget_id":"pnpm.pnpm",                            "check_cmd":["pnpm","--version"],              "version_url":"https://api.github.com/repos/pnpm/pnpm/releases/latest",                "web_url":"https://pnpm.io/installation",                                    "approx_mb":5,    "tags":["machine2"],                  "note":"Faster/smaller npm — great for monorepos"},
    {"name":"Bun",                      "category":"Runtimes & Languages",  "tier":RECOMMENDED, "winget_id":"Oven-sh.Bun",                          "check_cmd":["bun","--version"],               "version_url":"https://api.github.com/repos/oven-sh/bun/releases/latest",              "web_url":"https://bun.sh/",                                                 "approx_mb":80,   "tags":["recommended"],               "note":"Blazing fast JS runtime + package manager"},
    {"name":"Yarn",                     "category":"Runtimes & Languages",  "tier":OPTIONAL,    "winget_id":"Yarn.Yarn",                            "check_cmd":["yarn","--version"],              "version_url":"https://api.github.com/repos/yarnpkg/yarn/releases/latest",             "web_url":"https://yarnpkg.com/getting-started/install",                     "approx_mb":5,    "tags":["machine2"],                  "note":"Redundant if you have pnpm — pick one"},
    {"name":"Go",                       "category":"Runtimes & Languages",  "tier":OPTIONAL,    "winget_id":"GoLang.Go",                            "check_cmd":["go","version"],                  "version_url":None,                                                                    "web_url":"https://go.dev/dl/",                                              "approx_mb":400,  "tags":["recommended"],               "note":"Great for CLI tools and microservices"},
    {"name":"Rust (rustup)",            "category":"Runtimes & Languages",  "tier":OPTIONAL,    "winget_id":"Rustlang.Rustup",                      "check_cmd":["rustc","--version"],             "version_url":None,                                                                    "web_url":"https://www.rust-lang.org/tools/install",                         "approx_mb":700,  "tags":["recommended"],               "note":"Systems language — optional unless building Rust projects"},
    {"name":"Deno",                     "category":"Runtimes & Languages",  "tier":SKIP,        "winget_id":"DenoLand.Deno",                        "check_cmd":["deno","--version"],              "version_url":"https://api.github.com/repos/denoland/deno/releases/latest",            "web_url":"https://deno.com/",                                               "approx_mb":80,   "tags":["recommended"],               "note":"Skip unless specifically needed — Node covers most cases"},
    # ── AI & LLM ───────────────────────────────────────────
    {"name":"Claude Code",              "category":"AI & LLM",              "tier":ESSENTIAL,   "winget_id":None,                                   "check_cmd":["claude","--version"],            "version_url":None,                                                                    "web_url":"https://claude.ai/code",                                          "approx_mb":50,   "tags":["machine1","machine2","ai"],  "note":"Best AI coding agent — essential for AI engineers","install_cmd":["npm","install","-g","@anthropic-ai/claude-code"]},
    {"name":"Ollama",                   "category":"AI & LLM",              "tier":ESSENTIAL,   "winget_id":"Ollama.Ollama",                        "check_cmd":["ollama","--version"],            "version_url":"https://api.github.com/repos/ollama/ollama/releases/latest",            "web_url":"https://ollama.com/download",                                     "approx_mb":500,  "tags":["recommended","ai"],          "note":"Run Llama/Mistral/Phi locally — essential for offline AI"},
    {"name":"LM Studio",                "category":"AI & LLM",              "tier":RECOMMENDED, "winget_id":"LMStudio.LMStudio",                    "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://lmstudio.ai/",                                            "approx_mb":600,  "tags":["machine1","ai"],             "note":"GUI for running local LLMs — great for non-CLI users"},
    {"name":"Hugging Face CLI",         "category":"AI & LLM",              "tier":RECOMMENDED, "winget_id":None,                                   "check_cmd":["huggingface-cli","--help"],      "version_url":None,                                                                    "web_url":"https://huggingface.co/docs/huggingface_hub/guides/cli",          "approx_mb":20,   "tags":["recommended","ai"],          "note":"Download models/datasets from HuggingFace","install_cmd":["pip","install","huggingface_hub[cli]"]},
    {"name":"Aider (AI pair programmer)","category":"AI & LLM",             "tier":RECOMMENDED, "winget_id":None,                                   "check_cmd":["aider","--version"],             "version_url":"https://api.github.com/repos/paul-gauthier/aider/releases/latest",      "web_url":"https://aider.chat/",                                             "approx_mb":30,   "tags":["recommended","ai"],          "note":"Terminal AI coding assistant — great Claude Code alt","install_cmd":["pip","install","aider-chat"]},
    {"name":"Open WebUI",               "category":"AI & LLM",              "tier":RECOMMENDED, "winget_id":None,                                   "check_cmd":None,                              "version_url":"https://api.github.com/repos/open-webui/open-webui/releases/latest",    "web_url":"https://docs.openwebui.com/",                                     "approx_mb":500,  "tags":["recommended","ai"],          "note":"ChatGPT-like UI for Ollama — great for team LLM access","install_cmd":["pip","install","open-webui"]},
    {"name":"AnythingLLM",              "category":"AI & LLM",              "tier":OPTIONAL,    "winget_id":"Mintplex.AnythingLLM",                 "check_cmd":None,                              "version_url":"https://api.github.com/repos/Mintplex-Labs/anything-llm/releases/latest","web_url":"https://anythingllm.com/desktop",                                "approx_mb":600,  "tags":["recommended","ai"],          "note":"Full local RAG desktop app — optional if you build your own"},
    {"name":"Jan (local AI chat)",      "category":"AI & LLM",              "tier":OPTIONAL,    "winget_id":"Menlo.Jan",                            "check_cmd":None,                              "version_url":"https://api.github.com/repos/janhq/jan/releases/latest",                "web_url":"https://jan.ai/",                                                 "approx_mb":400,  "tags":["recommended","ai"],          "note":"Redundant with LM Studio — pick one"},
    {"name":"Langflow",                 "category":"AI & LLM",              "tier":OPTIONAL,    "winget_id":None,                                   "check_cmd":None,                              "version_url":"https://api.github.com/repos/logspace-ai/langflow/releases/latest",     "web_url":"https://www.langflow.org/",                                       "approx_mb":500,  "tags":["recommended","ai"],          "note":"Visual LangChain pipeline builder","install_cmd":["pip","install","langflow"]},
    {"name":"Flowise",                  "category":"AI & LLM",              "tier":OPTIONAL,    "winget_id":None,                                   "check_cmd":None,                              "version_url":"https://api.github.com/repos/FlowiseAI/Flowise/releases/latest",        "web_url":"https://flowiseai.com/",                                          "approx_mb":400,  "tags":["recommended","ai"],          "note":"Redundant with Langflow — pick one for visual AI pipelines","install_cmd":["npm","install","-g","flowise"]},
    {"name":"n8n (workflow automation)", "category":"AI & LLM",             "tier":OPTIONAL,    "winget_id":None,                                   "check_cmd":["n8n","--version"],               "version_url":"https://api.github.com/repos/n8n-io/n8n/releases/latest",               "web_url":"https://n8n.io/",                                                 "approx_mb":600,  "tags":["recommended","ai"],          "note":"Automation with AI nodes — install if you automate workflows","install_cmd":["npm","install","-g","n8n"]},
    {"name":"Continue (VS Code AI ext)","category":"AI & LLM",              "tier":SKIP,        "winget_id":None,                                   "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.continue.dev/",                                       "approx_mb":20,   "tags":["recommended","ai"],          "note":"Skip if using Cursor or Claude Code — redundant","install_cmd":["code","--install-extension","Continue.continue"]},
    # ── Terminal & CLI ─────────────────────────────────────
    {"name":"Windows Terminal",         "category":"Terminal & CLI",        "tier":ESSENTIAL,   "winget_id":"Microsoft.WindowsTerminal",            "check_cmd":None,                              "version_url":"https://api.github.com/repos/microsoft/terminal/releases/latest",       "web_url":"https://github.com/microsoft/terminal/releases",                  "approx_mb":30,   "tags":["machine1","machine2"],       "note":"Best Windows terminal — tabs, profiles, GPU rendering"},
    {"name":"fzf",                      "category":"Terminal & CLI",        "tier":ESSENTIAL,   "winget_id":"junegunn.fzf",                         "check_cmd":["fzf","--version"],               "version_url":"https://api.github.com/repos/junegunn/fzf/releases/latest",             "web_url":"https://github.com/junegunn/fzf",                                 "approx_mb":5,    "tags":["machine1","cli"],            "note":"Interactive fuzzy search — transforms CLI workflow"},
    {"name":"ripgrep",                  "category":"Terminal & CLI",        "tier":ESSENTIAL,   "winget_id":"BurntSushi.ripgrep.MSVC",              "check_cmd":["rg","--version"],                "version_url":"https://api.github.com/repos/BurntSushi/ripgrep/releases/latest",       "web_url":"https://github.com/BurntSushi/ripgrep",                           "approx_mb":5,    "tags":["machine1","cli"],            "note":"Fastest code search — replaces grep, used by VS Code"},
    {"name":"fd",                       "category":"Terminal & CLI",        "tier":ESSENTIAL,   "winget_id":"sharkdp.fd",                           "check_cmd":["fd","--version"],                "version_url":"https://api.github.com/repos/sharkdp/fd/releases/latest",               "web_url":"https://github.com/sharkdp/fd",                                   "approx_mb":4,    "tags":["machine1","cli"],            "note":"Fast intuitive file finder — replaces find command"},
    {"name":"jq",                       "category":"Terminal & CLI",        "tier":ESSENTIAL,   "winget_id":"jqlang.jq",                            "check_cmd":["jq","--version"],                "version_url":"https://api.github.com/repos/jqlang/jq/releases/latest",                "web_url":"https://jqlang.github.io/jq/",                                    "approx_mb":3,    "tags":["machine1","cli"],            "note":"Parse/transform JSON in terminal — essential for API work"},
    {"name":"zoxide",                   "category":"Terminal & CLI",        "tier":ESSENTIAL,   "winget_id":"ajeetdsouza.zoxide",                   "check_cmd":["zoxide","--version"],            "version_url":"https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest",       "web_url":"https://github.com/ajeetdsouza/zoxide",                           "approx_mb":3,    "tags":["machine1","cli"],            "note":"Remembers most-used dirs — smart cd replacement"},
    {"name":"Starship Prompt",          "category":"Terminal & CLI",        "tier":ESSENTIAL,   "winget_id":"Starship.Starship",                    "check_cmd":["starship","--version"],          "version_url":"https://api.github.com/repos/starship/starship/releases/latest",        "web_url":"https://starship.rs/",                                            "approx_mb":8,    "tags":["machine1","cli"],            "note":"Fast cross-shell prompt with git/lang context"},
    {"name":"cURL",                     "category":"Terminal & CLI",        "tier":ESSENTIAL,   "winget_id":"curl.curl",                            "check_cmd":["curl","--version"],              "version_url":"https://api.github.com/repos/curl/curl/releases/latest",                "web_url":"https://curl.se/windows/",                                        "approx_mb":5,    "tags":["machine1","cli"],            "note":"HTTP from terminal — fundamental dev tool"},
    {"name":"bat",                      "category":"Terminal & CLI",        "tier":RECOMMENDED, "winget_id":"sharkdp.bat",                          "check_cmd":["bat","--version"],               "version_url":"https://api.github.com/repos/sharkdp/bat/releases/latest",              "web_url":"https://github.com/sharkdp/bat",                                  "approx_mb":5,    "tags":["recommended","cli"],         "note":"cat with syntax highlighting + line numbers"},
    {"name":"eza",                      "category":"Terminal & CLI",        "tier":RECOMMENDED, "winget_id":"eza-community.eza",                    "check_cmd":["eza","--version"],               "version_url":"https://api.github.com/repos/eza-community/eza/releases/latest",        "web_url":"https://eza.rocks/",                                              "approx_mb":4,    "tags":["recommended","cli"],         "note":"ls with icons, colors, git status"},
    {"name":"delta",                    "category":"Terminal & CLI",        "tier":RECOMMENDED, "winget_id":"dandavison.delta",                     "check_cmd":["delta","--version"],             "version_url":"https://api.github.com/repos/dandavison/delta/releases/latest",         "web_url":"https://dandavison.github.io/delta/",                             "approx_mb":5,    "tags":["recommended","cli"],         "note":"Syntax-highlighted git diffs"},
    {"name":"yq",                       "category":"Terminal & CLI",        "tier":RECOMMENDED, "winget_id":"MikeFarah.yq",                         "check_cmd":["yq","--version"],                "version_url":"https://api.github.com/repos/mikefarah/yq/releases/latest",             "web_url":"https://github.com/mikefarah/yq",                                 "approx_mb":10,   "tags":["recommended","cli"],         "note":"jq for YAML — needed for K8s/docker-compose work"},
    {"name":"WezTerm",                  "category":"Terminal & CLI",        "tier":OPTIONAL,    "winget_id":"wez.wezterm",                          "check_cmd":["wezterm","--version"],           "version_url":"https://api.github.com/repos/wez/wezterm/releases/latest",              "web_url":"https://wezfurlong.org/wezterm/installation.html",                "approx_mb":50,   "tags":["machine1"],                  "note":"Powerful terminal — optional if Windows Terminal is enough"},
    {"name":"Wget",                     "category":"Terminal & CLI",        "tier":OPTIONAL,    "winget_id":"JernejSimoncic.Wget",                  "check_cmd":["wget","--version"],              "version_url":None,                                                                    "web_url":"https://eternallybored.org/misc/wget/",                           "approx_mb":2,    "tags":["machine1","cli"],            "note":"Redundant with curl — only if scripts require wget"},
    {"name":"glow",                     "category":"Terminal & CLI",        "tier":OPTIONAL,    "winget_id":"charmbracelet.glow",                   "check_cmd":["glow","--version"],              "version_url":"https://api.github.com/repos/charmbracelet/glow/releases/latest",       "web_url":"https://github.com/charmbracelet/glow",                           "approx_mb":10,   "tags":["recommended","cli"],         "note":"Render Markdown in terminal — nice for README previews"},
    {"name":"hyperfine",                "category":"Terminal & CLI",        "tier":SKIP,        "winget_id":"sharkdp.hyperfine",                    "check_cmd":["hyperfine","--version"],         "version_url":"https://api.github.com/repos/sharkdp/hyperfine/releases/latest",        "web_url":"https://github.com/sharkdp/hyperfine",                            "approx_mb":5,    "tags":["recommended","cli"],         "note":"CLI benchmarking — skip unless you benchmark commands often"},
    # ── Desktop & Productivity ─────────────────────────────
    {"name":"PowerToys",                "category":"Desktop & Productivity","tier":ESSENTIAL,   "winget_id":"Microsoft.PowerToys",                  "check_cmd":None,                              "version_url":"https://api.github.com/repos/microsoft/PowerToys/releases/latest",      "web_url":"https://github.com/microsoft/PowerToys/releases",                 "approx_mb":200,  "tags":["machine1","machine2"],       "note":"20+ tools: launcher, FancyZones, color picker, rename..."},
    {"name":"Everything",               "category":"Desktop & Productivity","tier":ESSENTIAL,   "winget_id":"voidtools.Everything",                 "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.voidtools.com/downloads/",                            "approx_mb":5,    "tags":["machine1","machine2"],       "note":"Instant file search — finds any file in milliseconds"},
    {"name":"Obsidian",                 "category":"Desktop & Productivity","tier":ESSENTIAL,   "winget_id":"Obsidian.Obsidian",                    "check_cmd":None,                              "version_url":"https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest","web_url":"https://obsidian.md/download",                                  "approx_mb":250,  "tags":["machine1","machine2"],       "note":"Knowledge base + notes — essential for documenting dev work"},
    {"name":"7-Zip",                    "category":"Desktop & Productivity","tier":RECOMMENDED, "winget_id":"7zip.7zip",                            "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.7-zip.org/download.html",                             "approx_mb":5,    "tags":["recommended"],               "note":"Essential archive tool — handles all formats"},
    {"name":"WizTree",                  "category":"Desktop & Productivity","tier":RECOMMENDED, "winget_id":"AntibodySoftware.WizTree",             "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.diskanalyzer.com/",                                   "approx_mb":5,    "tags":["machine1","machine2"],       "note":"See exactly what's eating your disk — fastest analyzer"},
    {"name":"GlazeWM",                  "category":"Desktop & Productivity","tier":OPTIONAL,    "winget_id":"glzr-io.glazewm",                      "check_cmd":["glazewm","--version"],           "version_url":"https://api.github.com/repos/glzr-io/glazewm/releases/latest",          "web_url":"https://github.com/glzr-io/glazewm/releases",                     "approx_mb":20,   "tags":["machine1"],                  "note":"Tiling WM — great for multi-window dev setups"},
    {"name":"Zebar",                    "category":"Desktop & Productivity","tier":OPTIONAL,    "winget_id":"glzr-io.zebar",                        "check_cmd":None,                              "version_url":"https://api.github.com/repos/glzr-io/zebar/releases/latest",            "web_url":"https://github.com/glzr-io/zebar/releases",                       "approx_mb":10,   "tags":["machine1"],                  "note":"Custom status bar — skip if not using GlazeWM"},
    {"name":"ExplorerPatcher",          "category":"Desktop & Productivity","tier":OPTIONAL,    "winget_id":"valinet.ExplorerPatcher",              "check_cmd":None,                              "version_url":"https://api.github.com/repos/valinet/ExplorerPatcher/releases/latest",  "web_url":"https://github.com/valinet/ExplorerPatcher/releases",             "approx_mb":5,    "tags":["machine1"],                  "note":"Win10-style taskbar on Win11 — aesthetic preference"},
    {"name":"AutoHotkey v2",            "category":"Desktop & Productivity","tier":OPTIONAL,    "winget_id":"AutoHotkey.AutoHotkey",                "check_cmd":None,                              "version_url":"https://api.github.com/repos/AutoHotkey/AutoHotkey/releases/latest",    "web_url":"https://www.autohotkey.com/",                                     "approx_mb":10,   "tags":["recommended"],               "note":"Windows automation — install if you automate repetitive tasks"},
    {"name":"LibreOffice",              "category":"Desktop & Productivity","tier":OPTIONAL,    "winget_id":"TheDocumentFoundation.LibreOffice",    "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.libreoffice.org/download/",                           "approx_mb":1500, "tags":["machine1"],                  "note":"Free Office suite — skip if you have Microsoft 365"},
    {"name":"Notion",                   "category":"Desktop & Productivity","tier":SKIP,        "winget_id":"Notion.Notion",                        "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.notion.so/desktop",                                   "approx_mb":300,  "tags":["recommended"],               "note":"Skip if using Obsidian — redundant for personal notes"},
    # ── Browsers ───────────────────────────────────────────
    {"name":"Google Chrome",            "category":"Browsers",              "tier":ESSENTIAL,   "winget_id":"Google.Chrome",                        "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.google.com/chrome/",                                  "approx_mb":800,  "tags":["machine1","machine2"],       "note":"Best DevTools, web testing, remote desktop"},
    {"name":"Brave",                    "category":"Browsers",              "tier":RECOMMENDED, "winget_id":"Brave.Brave",                          "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://brave.com/download/",                                     "approx_mb":800,  "tags":["machine1"],                  "note":"Privacy Chrome alt with built-in ad/tracker block"},
    {"name":"Zen Browser",              "category":"Browsers",              "tier":OPTIONAL,    "winget_id":"ZenBrowserDev.ZenBrowser",             "check_cmd":None,                              "version_url":"https://api.github.com/repos/zen-browser/desktop/releases/latest",     "web_url":"https://zen-browser.app/",                                        "approx_mb":300,  "tags":["machine1"],                  "note":"Minimalist Firefox-based browser — preference only"},
    {"name":"Microsoft Edge",           "category":"Browsers",              "tier":SKIP,        "winget_id":"Microsoft.Edge",                       "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.microsoft.com/en-us/edge/",                           "approx_mb":700,  "tags":["machine1","machine2"],       "note":"Pre-installed on Windows — skip manual install"},
    # ── Media & Communication ──────────────────────────────
    {"name":"Discord",                  "category":"Media & Communication", "tier":RECOMMENDED, "winget_id":"Discord.Discord",                      "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://discord.com/download",                                    "approx_mb":300,  "tags":["machine1"],                  "note":"Dev communities, team chat, AI/ML servers"},
    {"name":"Zoom",                     "category":"Media & Communication", "tier":RECOMMENDED, "winget_id":"Zoom.Zoom",                            "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://zoom.us/download",                                        "approx_mb":200,  "tags":["machine1"],                  "note":"Video meetings — still widely used in enterprise"},
    {"name":"Slack",                    "category":"Media & Communication", "tier":OPTIONAL,    "winget_id":"SlackTechnologies.Slack",               "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://slack.com/downloads/windows",                             "approx_mb":300,  "tags":["recommended"],               "note":"Team chat — install only if your company uses Slack"},
    {"name":"OBS Studio",               "category":"Media & Communication", "tier":OPTIONAL,    "winget_id":"OBSProject.OBSStudio",                 "check_cmd":None,                              "version_url":"https://api.github.com/repos/obsproject/obs-studio/releases/latest",    "web_url":"https://obsproject.com/download",                                 "approx_mb":400,  "tags":["machine1"],                  "note":"Screen recording + streaming — only if you record content"},
    {"name":"Discord PTB",              "category":"Media & Communication", "tier":OPTIONAL,    "winget_id":"Discord.Discord.PTB",                  "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://discord.com/download",                                    "approx_mb":300,  "tags":["machine2"],                  "note":"Public Test Build — redundant if stable Discord installed"},
    {"name":"JDownloader 2",            "category":"Media & Communication", "tier":OPTIONAL,    "winget_id":"AppWork.JDownloader",                  "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://jdownloader.org/download/index",                          "approx_mb":200,  "tags":["machine1"],                  "note":"Batch download manager — optional based on need"},
    {"name":"Spotify",                  "category":"Media & Communication", "tier":SKIP,        "winget_id":"Spotify.Spotify",                      "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://www.spotify.com/download/windows/",                       "approx_mb":300,  "tags":["recommended"],               "note":"Use web player to save 300MB disk space"},
    # ── Security & Network ─────────────────────────────────
    {"name":"Bitwarden",                "category":"Security & Network",    "tier":RECOMMENDED, "winget_id":"Bitwarden.Bitwarden",                  "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://bitwarden.com/download/",                                 "approx_mb":200,  "tags":["recommended"],               "note":"Free open-source password manager — essential security"},
    {"name":"Tailscale",                "category":"Security & Network",    "tier":RECOMMENDED, "winget_id":"tailscale.tailscale",                  "check_cmd":["tailscale","version"],           "version_url":"https://api.github.com/repos/tailscale/tailscale/releases/latest",      "web_url":"https://tailscale.com/download/windows",                          "approx_mb":50,   "tags":["recommended"],               "note":"Zero-config VPN between your machines — great for dev teams"},
    {"name":"Wireshark",                "category":"Security & Network",    "tier":OPTIONAL,    "winget_id":"WiresharkFoundation.Wireshark",        "check_cmd":["wireshark","--version"],         "version_url":None,                                                                    "web_url":"https://www.wireshark.org/download.html",                         "approx_mb":200,  "tags":["recommended"],               "note":"Network packet analyzer — only for network debugging"},
    {"name":"mitmproxy",                "category":"Security & Network",    "tier":OPTIONAL,    "winget_id":"mitmproxy.mitmproxy",                  "check_cmd":["mitmproxy","--version"],         "version_url":"https://api.github.com/repos/mitmproxy/mitmproxy/releases/latest",      "web_url":"https://mitmproxy.org/",                                          "approx_mb":50,   "tags":["recommended"],               "note":"HTTP intercepting proxy — for API debugging/testing"},
    # ── Document Tools ─────────────────────────────────────
    {"name":"Pandoc",                   "category":"Document Tools",        "tier":OPTIONAL,    "winget_id":"JohnMacFarlane.Pandoc",                "check_cmd":["pandoc","--version"],            "version_url":"https://api.github.com/repos/jgm/pandoc/releases/latest",               "web_url":"https://pandoc.org/installing.html",                              "approx_mb":100,  "tags":["machine1"],                  "note":"Convert between doc formats — needed for technical writing"},
    {"name":"MiKTeX (LaTeX)",           "category":"Document Tools",        "tier":SKIP,        "winget_id":"MiKTeX.MiKTeX",                        "check_cmd":None,                              "version_url":None,                                                                    "web_url":"https://miktex.org/download",                                     "approx_mb":800,  "tags":["machine1"],                  "note":"Skip unless writing academic papers — heavy 800MB"},
    {"name":"Tesseract OCR",            "category":"Document Tools",        "tier":OPTIONAL,    "winget_id":"UB-Mannheim.TesseractOCR",             "check_cmd":["tesseract","--version"],         "version_url":"https://api.github.com/repos/UB-Mannheim/tesseract/releases/latest",    "web_url":"https://github.com/UB-Mannheim/tesseract/wiki",                   "approx_mb":50,   "tags":["machine1"],                  "note":"OCR engine — install only if processing scanned docs"},
    # ── Monitoring ─────────────────────────────────────────
    {"name":"Prometheus (Docker)",      "category":"Monitoring",            "tier":OPTIONAL,    "winget_id":None,                                   "check_cmd":None,                              "version_url":"https://api.github.com/repos/prometheus/prometheus/releases/latest",    "web_url":"https://prometheus.io/download/",                                 "approx_mb":300,  "tags":["recommended"],               "note":"Metrics collection — pull via Docker when needed","install_cmd":["docker","pull","prom/prometheus"]},
    {"name":"Grafana (Docker)",         "category":"Monitoring",            "tier":OPTIONAL,    "winget_id":None,                                   "check_cmd":None,                              "version_url":"https://api.github.com/repos/grafana/grafana/releases/latest",          "web_url":"https://grafana.com/grafana/download",                            "approx_mb":500,  "tags":["recommended"],               "note":"Metrics dashboard — pull via Docker when needed","install_cmd":["docker","pull","grafana/grafana"]},
]
